[program:nodepop]
command=/home/ubuntu/.nvm/versions/node/v20.20.2/bin/node ./bin/www
directory=/home/ubuntu/nodepop
user=ubuntu
autostart=true
autorestart=true
startretries=3
stderr_logfile=/var/log/nodepop.err.log
stdout_logfile=/var/log/nodepop.out.log
environment=
    PORT="3000",
    MONGODB_URI="mongodb://127.0.0.1:27017/nodepop",
    SESSION_SECRET="CHANGE_ME"
